import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1B7278",
    alignItems: "center",
    justifyContent: "center",
  },
  titulo: {
    fontSize: 40,
    color: "#B8D8BA",
  },
  text: {
    color: "#DADADA",
    alignItems: "center",
    fontSize: 16,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  botao: {
    backgroundColor: "#26A69A",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
    width: 148,
    height: 46,
    alignItems: "center",
    position: "absolute",
    bottom: 20,
    right: 20,
  },
  textobotao: {
    fontSize: 16,
  },
  pontobranco: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#FFFFFF",
    marginHorizontal: 5,
    alignItems: "center",
    position: "absolute",
    bottom: 28,
    left: 35,
  },
  pontobranco2: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#FFFFFF",
    marginHorizontal: 5,
    alignItems: "center",
    position: "absolute",
    bottom: 28,
    left: 50,
  },
  pontopreto: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#000000ff",
    marginHorizontal: 5,
    alignItems: "center",
    position: "absolute",
    bottom: 28,
    left: 20,
  },
  pular: {
    color: "#FFFFFF",
    position: "absolute",
    top: 40,
    right: 20,
    alignItems: "center",
  },
});
